- hosts: myhost
  gather_facts: no
  tasks:
    - name: basic upload
      s3_sync:
        region: ap-northeast-1
        bucket: devopstrainingemidsjenkins
        file_root: /var/lib/jenkins/workspace/react/ReactJS/ReactJS-UnitTesting/build
